Repository cloudfoundry/docs-cf-cli, pull requests merged in 2020-06, with the labels that each got.

#64 Fix typo in migrate-service-instances
  v7.html.md.erb
Labels: unscheduled, unscheduled

#62 Remove lines indicating that TCP routing is not supported by the v7 CLI
  v7.html.md.erb
Labels: in progress, in progress

#63 added `map-route` to the table of changes
  v7.html.md.erb
Labels: scheduled

#65 Update v7.html.md.erb
  v7.html.md.erb
Labels: unscheduled, unscheduled

#66 Requirements for cf CLI v7
  v7.html.md.erb
Labels: in progress, in progress

#67 Requirements for cf CLI v7
  v7.html.md.erb
Labels: unscheduled, unscheduled
