Repository cloudfoundry/docs-cf-cli, pull requests merged in 2020-10, with the labels that each got.

#70 Added docs for breaking changes to `create-org` and `create-space`
  v7.html.md.erb
Labels: scheduled

#71 cf marketplace -e returns exit code 0 when no service offering is found
  v7.html.md.erb
Labels: scheduled

#72 13.5 v6 and v7 installation
  index.html.md.erb
  install-go-cli.html.md.erb
Labels: unscheduled, unscheduled

#73 Document removal of service column from cf routes
  v7.html.md.erb
Labels: in progress, in progress
